import Link from 'next/link';
import Image from 'next/image';
import { formatDistance } from 'date-fns';
import { Card, CardContent } from './ui/card';

export default function BlogCard({ data, isNew }) {
    return (
        <Link href='/test' className='flex group @container h-full transition-transform duration-300 transform-gpu rounded border bg-background'>
            <div className='flex flex-row flex-1 relative h-full'>
                <div className='z-1 flex-1'>
                    <div className='flex flex-col gap-2 px-4 py-4'>
                    <h2 className="text-lg font-medium leading-5 w-fit text-primary">
                        {data.title}
                    </h2>
                    <p className="text-sm text-muted-foreground whitespace-normal leading-6">
                        {data.description}
                    </p>
                    <time className="text-xs text-primary leading-3" dateTime={data.date.toString()}>
                        Posted {formatDistance(data.date, new Date(), { addSuffix: true })}
                    </time>
                    </div>
                    <hr className="w-full article-bottom-border h-[1px]" />
                    <ul className="flex px-4 py-2 gap-2 flex-wrap text-xs text-primary">
                        <div className="text-primary">
                            {data.readingTime}
                        </div>
                        <div className="h-full w-[1px] bg-body-700 mr-2"></div>
                        {data.tags.map((tag, index) => <div key={index} className="pr-2">{tag}</div>)}
                    </ul>
                </div>
                <div style={{ aspectRatio: '16/9' }} className="hidden sm:block display-none @xl:display-block ml-auto overflow-hidden rounded overflow-hidden z-2 max-w-[200px] w-full object-cover h-full ml-auto flex-shrink-0">
                    <img src="/banner.png" alt="Banner for article generated by midjourney" loading="lazy" className="article-image object-cover absolute min-w-[200px] w-auto max-w-[200px] right-0 z-1 rounded-r image-overlay transition-all h-full" width="500" height="280" decoding="async" />
                </div>
            </div>
        </Link>
    )
}