name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - deveploment

jobs:
    deploy-preview:
    permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Vercel CLI
          run: yarn add --dev vercel@latest
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        - name: Build Project Artifacts
          run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        - name: Deploy Preview
          id: deploy
          run: echo preview_url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}) >> $GITHUB_OUTPUT
        - name: Comment on Push Request
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}